SoundPlay, 1.wav, Wait
SoundPlay, 3.wav, Wait
SoundPlay, 7.wav, Wait
SoundPlay, 0.wav, Wait
SoundPlay, 1.wav, Wait
SoundPlay, 6.wav, Wait
SoundPlay, 7.wav, Wait
SoundPlay, 3.wav, Wait
SoundPlay, 4.wav, Wait
SoundPlay, 5.wav, Wait
SoundPlay, 0.wav, Wait